feat(cli): update modo from yaml file
sdsc-ordes/modos-api pull request #89
Opened 2024-07-24 15:04 UTC by almutlue

### Objective:
Add cli function to group update modo based on a yaml file. By default, this function will update existing elements, add new elements and remove elements that are not specified in the yaml, but part of modo. `--no-remove` flag can be set to prevent deletion of elements.

### Notes:
- I think `modo.from_file()` should have the same behavior and by default remove objects that are not specified in the yaml any longer. 
- I realized that there is no need to specify the modo itself in the yaml file, as modo just needs the `object_directory` and we require `object_directory()` as input argument anyways.

### Limitations:
- I did not add an `--element-id` flag, as it is the same as running `--no-remove` with a yaml only specifying the element to change.

### Questions: 
I realized that  `modo.update_element()` does accept a `source-file` or `part-of` argument. So if you want to update files, you would have to first remove the element and then run `update`. This also means that in `modo.from_file()` and `modos update` changes in the `args` part of the yaml file will be ignored. Should we change this? And if yes should this be part of this PR or a new one?

2024-07-25 11:04 UTC, cmdoret requested changes
Nice, this will be very useful! :+1: 
Added a few suggestions to make the CLI more intuitive

2024-07-25 11:04 UTC, cmdoret commented on modos/api.py
> +            modo_id = modo_dict.get("meta", {}).get("id") or modo.path.name
**question:** could we not always get `id` from `modo`?
**suggestion** use `modo_id = modo.zarr['/'].attrs['id']`

2024-07-26 12:55 UTC, almutlue commented on modos/cli.py
> +    ] = None,
Good point, yes it should definitely be mandatory. Happy to make it an option :+1:

2024-07-26 13:24 UTC, cmdoret approved these changes
:+1: Perfect!

2024-07-26 13:32 UTC, merged